name : Advisora Deployment


on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Notify pipline trigger
        run: echo "pipline is triggered"

   
